apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  template:
     metadata:
       labels:
         app: spring
     spec:
       containers:
       - name: spring
         image: sarrag/spring:1.0.1
         ports:
           - containerPort: 8080
         envFrom:
           - configMapRef:
               name: spring-config
           - secretRef:
               name: postgres-secret
---
apiVersion: v1
kind: Service
metadata:
  name: spring-deploy-svc
spec:
  selector:
    app: spring
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080